"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type View = "today" | "coach" | "plan" | "history" | "live";
const movements = ["Goblet squat", "Romanian deadlift", "Reverse lunge", "Dead bug"];

export default function Home() {
  const [view, setView] = useState<View>("today");
  const [complete, setComplete] = useState([true, false, false, false]);
  const [chat, setChat] = useState(["You’re set for lower-body strength today. Want to train now, or adjust the session?", "My knees feel a little stiff today.", "Let’s keep the range comfortable. I’ll switch reverse lunges for supported split squats and cue a slower descent."]);
  const [draft, setDraft] = useState("");
  const [listening, setListening] = useState(false);
  const [cameraOn, setCameraOn] = useState(false);
  const [cameraError, setCameraError] = useState("");
  const video = useRef<HTMLVideoElement>(null);

  function go(next: View) { if (view === "live" && next !== "live") stopCamera(); setView(next); }
  function stopCamera() { const stream = video.current?.srcObject as MediaStream | null; stream?.getTracks().forEach((track) => track.stop()); if (video.current) video.current.srcObject = null; setCameraOn(false); }
  useEffect(() => () => { const stream = video.current?.srcObject as MediaStream | null; stream?.getTracks().forEach((track) => track.stop()); }, []);
  async function startCamera() { setCameraError(""); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: false }); if (video.current) { video.current.srcObject = stream; await video.current.play(); } setCameraOn(true); } catch { setCameraError("Camera access is needed for the on-device pose preview. Check browser permission and try again."); } }
  function send(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return; setChat([...chat, draft.trim(), "Got it. I’ve noted that for this session. Keep the movement smooth and stop if anything feels sharp or unusual."]); setDraft(""); }
  const nav: [View, string, string][] = [["today", "⌁", "Today"], ["coach", "◌", "Coach"], ["plan", "▤", "Plan"], ["history", "◴", "History"]];

  return <main className="app-shell">
    <aside className="sidebar"><button className="brand" onClick={() => go("today")}><span>F</span>FitAI <i>Coach</i></button><p className="label">YOUR WORKSPACE</p><nav>{nav.map(([id, icon, name]) => <button key={id} onClick={() => go(id)} className={view === id ? "active" : ""}><span>{icon}</span>{name}</button>)}</nav><div className="sidebar-foot"><p>✦ Fitness guidance, not medical care.</p><button className="profile"><b>BG</b><span><strong>Bharat Goyal</strong><small>Beginner · 2 weeks in</small></span>⌄</button></div></aside>
    <section className="main"><header className="topbar"><span><i /> SYSTEMS NORMAL &nbsp; · &nbsp; Wednesday, Aug 19</span><div>⌁ &nbsp; ⚙</div></header><header className="mobile-top"><button className="brand" onClick={() => go("today")}><span>F</span>FitAI <i>Coach</i></button>⚙</header>
      {view === "today" && <Today complete={complete} setComplete={setComplete} start={() => go("live")} coach={() => go("coach")} />}
      {view === "coach" && <Coach chat={chat} draft={draft} setDraft={setDraft} send={send} listening={listening} setListening={setListening} start={() => go("live")} />}
      {view === "plan" && <Plan start={() => go("live")} />}
      {view === "history" && <History />}
      {view === "live" && <Live video={video} cameraOn={cameraOn} cameraError={cameraError} startCamera={startCamera} stopCamera={stopCamera} exit={() => go("today")} />}
    </section>
  </main>;
}

function Today({ complete, setComplete, start, coach }: { complete: boolean[]; setComplete: (items: boolean[]) => void; start: () => void; coach: () => void }) {
  return <div className="wrap"><section className="intro"><div><p className="label">WEDNESDAY · SESSION 06</p><h1>Build strength, <em>at your pace.</em></h1><p>A focused lower-body session built around your recent training and today’s check-in.</p></div><div className="streak">✦ <span><b>4 day streak</b><small>Your most consistent week yet.</small></span></div></section>
    <section className="hero"><div><p className="label">TODAY’S SESSION</p><h2>Lower-body<br />strength</h2><p>35 min · Dumbbell · Beginner friendly</p><div className="chips"><span>Form-first</span><span>Audio cues on</span></div><button className="primary" onClick={start}>Start live session <b>→</b></button></div><div className="pose-art"><i /><i /><b /><b /><b /></div></section>
    <section className="grid"><div className="card flow"><header><div><p className="label">SESSION FLOW</p><h3>{complete.filter(Boolean).length} of 4 movements complete</h3></div><button onClick={start}>View live →</button></header>{movements.map((item, index) => <button className="movement" key={item} onClick={() => { const next = [...complete]; next[index] = !next[index]; setComplete(next); }}><i className={complete[index] ? "done" : ""}>{complete[index] ? "✓" : index + 1}</i><span><b>{item}</b><small>{index === 0 ? "3 × 10 · Tempo: 3 seconds down" : index === 1 ? "3 × 10 · Keep ribs stacked" : index === 2 ? "3 × 8 / side · Drive through front heel" : "3 × 10 / side · Slow, controlled reps"}</small></span><em>›</em></button>)}</div><aside className="rail"><div className="card readiness"><p className="label">TODAY’S READINESS</p><div><b>82</b><span>/100</span><i>Ready to train</i></div><strong><i /></strong><small>Based on your check-in, last session and recovery rhythm.</small></div><div className="card ask"><b>✦</b><div><p className="label">ASK YOUR COACH</p><h3>Not feeling today’s plan?</h3><p>Tell Coach what’s changed and get a safe adjustment.</p><button onClick={coach}>Talk to Coach →</button></div></div></aside></section></div>;
}

function Coach({ chat, draft, setDraft, send, listening, setListening, start }: { chat: string[]; draft: string; setDraft: (text: string) => void; send: (event: FormEvent) => void; listening: boolean; setListening: (value: boolean) => void; start: () => void }) {
  return <div className="wrap"><section className="intro"><div><p className="label">COACH CONVERSATION</p><h1>Your calm, <em>real-time guide.</em></h1><p>Ask about your plan, get a movement adjustment, or start a guided session.</p></div><button className="outline" onClick={start}>Start workout →</button></section><section className="coach-layout"><div className="card chat"><header><span>✦</span><div><b>FitAI Coach</b><small><i /> Available for your session</small></div></header><div className="messages">{chat.map((item, index) => <div className={index % 2 ? "mine" : "theirs"} key={`${item}-${index}`}><i>{index % 2 ? "BG" : "✦"}</i><p>{item}</p></div>)}</div><form onSubmit={send}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Ask about today’s session…" /><button type="button" className={listening ? "recording" : ""} onClick={() => setListening(!listening)}>◉</button><button type="submit">↑</button></form><small>{listening ? "Listening — tap again to stop" : "Push-to-talk keeps voice questions intentional and private."}</small></div><aside className="coach-rail"><div className="card"><p className="label">TODAY’S CONTEXT</p><h3>Lower-body strength</h3><dl><div><dt>Focus</dt><dd>Form & confidence</dd></div><div><dt>Equipment</dt><dd>One dumbbell</dd></div><div><dt>Adjustment</dt><dd>Supported split squat</dd></div></dl></div><div className="card safety">⌁ <p>Coach will never diagnose pain or replace clinical advice. It will recommend you pause and seek support when needed.</p></div></aside></section></div>;
}

function Plan({ start }: { start: () => void }) { const days = [["MON", "17", "Full-body foundation", "Complete"], ["WED", "19", "Lower-body strength", "Today"], ["FRI", "21", "Mobility + core", "Up next"]]; return <div className="wrap"><section className="intro"><div><p className="label">ADAPTIVE TRAINING PLAN</p><h1>A plan that <em>meets you there.</em></h1><p>Structured sessions from a curated library, adapted to your equipment and feedback.</p></div><button className="primary" onClick={start}>Start next session →</button></section><div className="plan-band"><b>03</b><span><strong>Three sessions this week</strong><small>Strength · mobility · recovery, with room for your real life.</small></span>↗</div><section className="days">{days.map(([day, date, name, status]) => <article key={day} className={status === "Today" ? "today" : ""}><p>{day}</p><b>{date}</b><i>{status === "Complete" ? "✓" : status === "Today" ? "⌁" : "○"}</i><h3>{name}</h3><small>{status} · 30–40 min</small></article>)}</section><section className="card why"><b>✦</b><div><p className="label">WHY THIS PLAN</p><h3>Progress without the all-or-nothing pressure.</h3><p>Your coach uses your history, check-ins and selected equipment to choose from reviewed movement options. You stay in control of every adjustment.</p></div></section></div>; }

function History() { return <div className="wrap"><section className="intro"><div><p className="label">TRAINING HISTORY</p><h1>Small wins, <em>made visible.</em></h1><p>A calm view of the consistency and confidence you’re building.</p></div></section><section className="history"><div className="card calendar"><header><div><p className="label">AUGUST</p><h3>Your rhythm</h3></div><small>● Trained</small></header><div>{Array.from({ length: 28 }, (_, i) => <span className={[1, 3, 8, 10, 15, 17, 18].includes(i) ? "trained" : ""} key={i}>{i + 1}</span>)}</div></div><div className="card stats"><p className="label">THIS MONTH</p><div><b>8</b><small>sessions completed</small></div><div><b>4</b><small>week best streak</small></div><div><b>91%</b><small>planned sessions kept</small></div></div></section><section className="card reflection"><p className="label">LAST SESSION</p><h3>“I felt more steady on the deadlifts.”</h3><p>You noted improved balance and chose to keep the same load. Your next session is set up to build from there.</p></section></div>; }

function Live({ video, cameraOn, cameraError, startCamera, stopCamera, exit }: { video: React.RefObject<HTMLVideoElement | null>; cameraOn: boolean; cameraError: string; startCamera: () => void; stopCamera: () => void; exit: () => void }) { return <div className="live"><header><button onClick={exit}>← End session</button><span>● LIVE FORM SESSION</span><b>08:42</b></header><section><div className="camera"><video className={cameraOn ? "" : "hide"} ref={video} muted playsInline />{cameraOn ? <><div className="tracking" /><small>● Local video preview</small><button className="off" onClick={stopCamera}>Turn camera off</button></> : <div className="camera-empty"><i>⌁</i><h2>Your camera stays here.</h2><p>Turn it on when you’re ready. The intended pose analysis runs locally in the browser.</p><button className="primary" onClick={startCamera}>Enable camera →</button>{cameraError && <small>{cameraError}</small>}</div>}</div><aside><p className="label">MOVEMENT 2 OF 4</p><h1>Romanian<br /><em>deadlift</em></h1><p>3 sets × 10 reps</p><div className="cue"><b>✦</b><p className="label">COACH CUE</p><h3>“Keep your chest long as you hinge back.”</h3><small>Your live cues will appear here after on-device pose tracking is connected.</small></div><div className="reps"><span><p className="label">CURRENT SET</p><b>0 <i>/ 10</i></b></span><button className="outline">Mark set done</button></div><footer><button>Skip movement</button><button>Need an adjustment →</button></footer></aside></section></div>; }
